security:

    firewalls:
        wsse_secured:
            # pattern:   /api/.*
            # pattern:   /.*
            pattern: ^/
            anonymous: ~
            wsse:      true
            # wsse:      { nonce_dir: null, lifetime: 300, realm: "Secured API", profile: "UsernameToken" }

    access_control:

        -
            path: ^/bundle
            role: IS_AUTHENTICATED_ANONYMOUSLY

        -
            path: ^/_profiler
            role: IS_AUTHENTICATED_ANONYMOUSLY

        -
            path: ^/_wdt
            role: IS_AUTHENTICATED_ANONYMOUSLY

        -
            path: ^/login
            role: IS_AUTHENTICATED_ANONYMOUSLY

        -
            path: ^/api/.*
            role: ROLE_AUTHENTICATED_USER

        -
            path: ^/
            role: ROLE_AUTHENTICATED_USER

    providers:
        default_provider:
             id: matmar10_todo.webservice_user_provider
