security:

    firewalls:
        wsse_secured:
            pattern: ^/.*
            anonymous: ~
            wsse:      true
            logout:
                path:   /logout
                target: /

    access_control:

        -
            path: ^/bundle
            role: IS_AUTHENTICATED_ANONYMOUSLY

        -
            path: ^/_profiler
            role: IS_AUTHENTICATED_ANONYMOUSLY

        -
            path: ^/_wdt
            role: IS_AUTHENTICATED_ANONYMOUSLY

        -
            path: ^/login
            role: IS_AUTHENTICATED_ANONYMOUSLY

        -
            path: ^/login/authenticate-with-twitter
            role: IS_AUTHENTICATED_ANONYMOUSLY

        -
            path: ^/login/check-twitter-authentication
            role: IS_AUTHENTICATED_ANONYMOUSLY

        -
            path: ^/
            role: ROLE_AUTHENTICATED_USER


    providers:
        default_provider:
             id: matmar10_todo.webservice_user_provider
